//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostname) DeepCopyInto(out *CustomHostname) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostname.
func (in *CustomHostname) DeepCopy() *CustomHostname {
	if in == nil {
		return nil
	}
	out := new(CustomHostname)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomHostname) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameList) DeepCopyInto(out *CustomHostnameList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomHostname, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameList.
func (in *CustomHostnameList) DeepCopy() *CustomHostnameList {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomHostnameList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameSSL) DeepCopyInto(out *CustomHostnameSSL) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameSSL.
func (in *CustomHostnameSSL) DeepCopy() *CustomHostnameSSL {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameSSL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameSSLStatus) DeepCopyInto(out *CustomHostnameSSLStatus) {
	*out = *in
	if in.ExpiresOn != nil {
		in, out := &in.ExpiresOn, &out.ExpiresOn
		*out = (*in).DeepCopy()
	}
	if in.ValidationRecords != nil {
		in, out := &in.ValidationRecords, &out.ValidationRecords
		*out = make([]SSLValidationRecord, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ValidationErrors != nil {
		in, out := &in.ValidationErrors, &out.ValidationErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameSSLStatus.
func (in *CustomHostnameSSLStatus) DeepCopy() *CustomHostnameSSLStatus {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameSSLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameSpec) DeepCopyInto(out *CustomHostnameSpec) {
	*out = *in
	if in.OriginSNI != nil {
		in, out := &in.OriginSNI, &out.OriginSNI
		*out = new(string)
		**out = **in
	}
	out.ZoneRef = in.ZoneRef
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(CustomHostnameSSL)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameSpec.
func (in *CustomHostnameSpec) DeepCopy() *CustomHostnameSpec {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomHostnameStatus) DeepCopyInto(out *CustomHostnameStatus) {
	*out = *in
	if in.SSL != nil {
		in, out := &in.SSL, &out.SSL
		*out = new(CustomHostnameSSLStatus)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomHostnameStatus.
func (in *CustomHostnameStatus) DeepCopy() *CustomHostnameStatus {
	if in == nil {
		return nil
	}
	out := new(CustomHostnameStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSLValidationRecord) DeepCopyInto(out *SSLValidationRecord) {
	*out = *in
	if in.Emails != nil {
		in, out := &in.Emails, &out.Emails
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSLValidationRecord.
func (in *SSLValidationRecord) DeepCopy() *SSLValidationRecord {
	if in == nil {
		return nil
	}
	out := new(SSLValidationRecord)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneRef) DeepCopyInto(out *ZoneRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneRef.
func (in *ZoneRef) DeepCopy() *ZoneRef {
	if in == nil {
		return nil
	}
	out := new(ZoneRef)
	in.DeepCopyInto(out)
	return out
}
