---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domains.cf-edge.io
  resources:
  - zones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - domains.cf-edge.io
  resources:
  - zones/finalizers
  verbs:
  - update
- apiGroups:
  - domains.cf-edge.io
  resources:
  - zones/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - loadbalancing.cf-edge.io
  resources:
  - accounts
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadbalancing.cf-edge.io
  resources:
  - accounts/status
  - loadbalancermonitors/status
  - loadbalancerpools/status
  - loadbalancers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - loadbalancing.cf-edge.io
  resources:
  - loadbalancermonitors
  - loadbalancerpools
  - loadbalancers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - loadbalancing.cf-edge.io
  resources:
  - loadbalancermonitors/finalizers
  - loadbalancerpools/finalizers
  - loadbalancers/finalizers
  verbs:
  - update
- apiGroups:
  - saas.cf-edge.io
  resources:
  - customhostnames
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - saas.cf-edge.io
  resources:
  - customhostnames/finalizers
  verbs:
  - update
- apiGroups:
  - saas.cf-edge.io
  resources:
  - customhostnames/status
  verbs:
  - get
  - patch
  - update
