apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cf-edge-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cf-edge-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cf-edge-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cf-edge-operator
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "cf-edge-operator.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 10
      containers:
      - name: manager
        image: {{ include "cf-edge-operator.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --metrics-secure=false
        - --operator-namespace={{ include "cf-edge-operator.operatorNamespace" . }}
        - --delete-policy={{ .Values.deletePolicy }}
        {{- if .Values.dryRun }}
        - --dry-run
        {{- end }}
        {{- if .Values.leaderElect }}
        - --leader-elect
        {{- end }}
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
