{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cf-edge-operator.fullname" . }}
  labels:
    {{- include "cf-edge-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "cf-edge-operator.selectorLabels" . | nindent 6 }}
{{- end }}
