{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cf-edge-operator.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cf-edge-operator.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: cf-edge-operator
      app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
