apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cf-edge-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cf-edge-operator.labels" . | nindent 4 }}
