## Append samples of your project ##
resources:
- saas_v1beta1_customhostname.yaml
- domains_v1beta1_zone.yaml
- accounts_v1beta1_account.yaml
- loadbalancing_v1beta1_loadbalancermonitor.yaml
- loadbalancing_v1beta1_loadbalancerpool.yaml
- loadbalancing_v1beta1_loadbalancer.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
