//go:build !ignore_autogenerated

/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccountRef) DeepCopyInto(out *AccountRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccountRef.
func (in *AccountRef) DeepCopy() *AccountRef {
	if in == nil {
		return nil
	}
	out := new(AccountRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancer) DeepCopyInto(out *LoadBalancer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancer.
func (in *LoadBalancer) DeepCopy() *LoadBalancer {
	if in == nil {
		return nil
	}
	out := new(LoadBalancer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerAdaptiveRouting) DeepCopyInto(out *LoadBalancerAdaptiveRouting) {
	*out = *in
	if in.FailoverAcrossPools != nil {
		in, out := &in.FailoverAcrossPools, &out.FailoverAcrossPools
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerAdaptiveRouting.
func (in *LoadBalancerAdaptiveRouting) DeepCopy() *LoadBalancerAdaptiveRouting {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerAdaptiveRouting)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerList) DeepCopyInto(out *LoadBalancerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerList.
func (in *LoadBalancerList) DeepCopy() *LoadBalancerList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerLocationStrategy) DeepCopyInto(out *LoadBalancerLocationStrategy) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerLocationStrategy.
func (in *LoadBalancerLocationStrategy) DeepCopy() *LoadBalancerLocationStrategy {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerLocationStrategy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerMonitor) DeepCopyInto(out *LoadBalancerMonitor) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerMonitor.
func (in *LoadBalancerMonitor) DeepCopy() *LoadBalancerMonitor {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerMonitor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerMonitor) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerMonitorList) DeepCopyInto(out *LoadBalancerMonitorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerMonitor, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerMonitorList.
func (in *LoadBalancerMonitorList) DeepCopy() *LoadBalancerMonitorList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerMonitorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerMonitorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerMonitorRef) DeepCopyInto(out *LoadBalancerMonitorRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerMonitorRef.
func (in *LoadBalancerMonitorRef) DeepCopy() *LoadBalancerMonitorRef {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerMonitorRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerMonitorSpec) DeepCopyInto(out *LoadBalancerMonitorSpec) {
	*out = *in
	out.AccountRef = in.AccountRef
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(map[string][]string)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]string, len(*in))
			for key, val := range *in {
				var outVal []string
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]string, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerMonitorSpec.
func (in *LoadBalancerMonitorSpec) DeepCopy() *LoadBalancerMonitorSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerMonitorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerMonitorStatus) DeepCopyInto(out *LoadBalancerMonitorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerMonitorStatus.
func (in *LoadBalancerMonitorStatus) DeepCopy() *LoadBalancerMonitorStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerMonitorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerOriginHeader) DeepCopyInto(out *LoadBalancerOriginHeader) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerOriginHeader.
func (in *LoadBalancerOriginHeader) DeepCopy() *LoadBalancerOriginHeader {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerOriginHeader)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPool) DeepCopyInto(out *LoadBalancerPool) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPool.
func (in *LoadBalancerPool) DeepCopy() *LoadBalancerPool {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPool)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerPool) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolList) DeepCopyInto(out *LoadBalancerPoolList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]LoadBalancerPool, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolList.
func (in *LoadBalancerPoolList) DeepCopy() *LoadBalancerPoolList {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *LoadBalancerPoolList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolLoadShedding) DeepCopyInto(out *LoadBalancerPoolLoadShedding) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolLoadShedding.
func (in *LoadBalancerPoolLoadShedding) DeepCopy() *LoadBalancerPoolLoadShedding {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolLoadShedding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolOrigin) DeepCopyInto(out *LoadBalancerPoolOrigin) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Header != nil {
		in, out := &in.Header, &out.Header
		*out = new(LoadBalancerOriginHeader)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolOrigin.
func (in *LoadBalancerPoolOrigin) DeepCopy() *LoadBalancerPoolOrigin {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolOrigin)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolOriginSteering) DeepCopyInto(out *LoadBalancerPoolOriginSteering) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolOriginSteering.
func (in *LoadBalancerPoolOriginSteering) DeepCopy() *LoadBalancerPoolOriginSteering {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolOriginSteering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolRef) DeepCopyInto(out *LoadBalancerPoolRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolRef.
func (in *LoadBalancerPoolRef) DeepCopy() *LoadBalancerPoolRef {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolSpec) DeepCopyInto(out *LoadBalancerPoolSpec) {
	*out = *in
	out.AccountRef = in.AccountRef
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]LoadBalancerPoolOrigin, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.MonitorRef != nil {
		in, out := &in.MonitorRef, &out.MonitorRef
		*out = new(LoadBalancerMonitorRef)
		**out = **in
	}
	if in.OriginSteering != nil {
		in, out := &in.OriginSteering, &out.OriginSteering
		*out = new(LoadBalancerPoolOriginSteering)
		**out = **in
	}
	if in.CheckRegions != nil {
		in, out := &in.CheckRegions, &out.CheckRegions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoadShedding != nil {
		in, out := &in.LoadShedding, &out.LoadShedding
		*out = new(LoadBalancerPoolLoadShedding)
		**out = **in
	}
	if in.Latitude != nil {
		in, out := &in.Latitude, &out.Latitude
		*out = new(string)
		**out = **in
	}
	if in.Longitude != nil {
		in, out := &in.Longitude, &out.Longitude
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolSpec.
func (in *LoadBalancerPoolSpec) DeepCopy() *LoadBalancerPoolSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolStatus) DeepCopyInto(out *LoadBalancerPoolStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolStatus.
func (in *LoadBalancerPoolStatus) DeepCopy() *LoadBalancerPoolStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerPoolWeight) DeepCopyInto(out *LoadBalancerPoolWeight) {
	*out = *in
	out.PoolRef = in.PoolRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerPoolWeight.
func (in *LoadBalancerPoolWeight) DeepCopy() *LoadBalancerPoolWeight {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerPoolWeight)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerRandomSteering) DeepCopyInto(out *LoadBalancerRandomSteering) {
	*out = *in
	if in.PoolWeights != nil {
		in, out := &in.PoolWeights, &out.PoolWeights
		*out = make([]LoadBalancerPoolWeight, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerRandomSteering.
func (in *LoadBalancerRandomSteering) DeepCopy() *LoadBalancerRandomSteering {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerRandomSteering)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSessionAffinityAttributes) DeepCopyInto(out *LoadBalancerSessionAffinityAttributes) {
	*out = *in
	if in.Headers != nil {
		in, out := &in.Headers, &out.Headers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.RequireAllHeaders != nil {
		in, out := &in.RequireAllHeaders, &out.RequireAllHeaders
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSessionAffinityAttributes.
func (in *LoadBalancerSessionAffinityAttributes) DeepCopy() *LoadBalancerSessionAffinityAttributes {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSessionAffinityAttributes)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerSpec) DeepCopyInto(out *LoadBalancerSpec) {
	*out = *in
	out.ZoneRef = in.ZoneRef
	if in.DefaultPoolRefs != nil {
		in, out := &in.DefaultPoolRefs, &out.DefaultPoolRefs
		*out = make([]LoadBalancerPoolRef, len(*in))
		copy(*out, *in)
	}
	out.FallbackPoolRef = in.FallbackPoolRef
	if in.Proxied != nil {
		in, out := &in.Proxied, &out.Proxied
		*out = new(bool)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RegionPools != nil {
		in, out := &in.RegionPools, &out.RegionPools
		*out = new(map[string][]LoadBalancerPoolRef)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]LoadBalancerPoolRef, len(*in))
			for key, val := range *in {
				var outVal []LoadBalancerPoolRef
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]LoadBalancerPoolRef, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.CountryPools != nil {
		in, out := &in.CountryPools, &out.CountryPools
		*out = new(map[string][]LoadBalancerPoolRef)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]LoadBalancerPoolRef, len(*in))
			for key, val := range *in {
				var outVal []LoadBalancerPoolRef
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]LoadBalancerPoolRef, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.PopPools != nil {
		in, out := &in.PopPools, &out.PopPools
		*out = new(map[string][]LoadBalancerPoolRef)
		if **in != nil {
			in, out := *in, *out
			*out = make(map[string][]LoadBalancerPoolRef, len(*in))
			for key, val := range *in {
				var outVal []LoadBalancerPoolRef
				if val == nil {
					(*out)[key] = nil
				} else {
					inVal := (*in)[key]
					in, out := &inVal, &outVal
					*out = make([]LoadBalancerPoolRef, len(*in))
					copy(*out, *in)
				}
				(*out)[key] = outVal
			}
		}
	}
	if in.SessionAffinityAttributes != nil {
		in, out := &in.SessionAffinityAttributes, &out.SessionAffinityAttributes
		*out = new(LoadBalancerSessionAffinityAttributes)
		(*in).DeepCopyInto(*out)
	}
	if in.AdaptiveRouting != nil {
		in, out := &in.AdaptiveRouting, &out.AdaptiveRouting
		*out = new(LoadBalancerAdaptiveRouting)
		(*in).DeepCopyInto(*out)
	}
	if in.LocationStrategy != nil {
		in, out := &in.LocationStrategy, &out.LocationStrategy
		*out = new(LoadBalancerLocationStrategy)
		**out = **in
	}
	if in.RandomSteering != nil {
		in, out := &in.RandomSteering, &out.RandomSteering
		*out = new(LoadBalancerRandomSteering)
		(*in).DeepCopyInto(*out)
	}
	if in.Networks != nil {
		in, out := &in.Networks, &out.Networks
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerSpec.
func (in *LoadBalancerSpec) DeepCopy() *LoadBalancerSpec {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoadBalancerStatus) DeepCopyInto(out *LoadBalancerStatus) {
	*out = *in
	if in.ResolvedDefaultPoolIDs != nil {
		in, out := &in.ResolvedDefaultPoolIDs, &out.ResolvedDefaultPoolIDs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.UnresolvedPoolRefs != nil {
		in, out := &in.UnresolvedPoolRefs, &out.UnresolvedPoolRefs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoadBalancerStatus.
func (in *LoadBalancerStatus) DeepCopy() *LoadBalancerStatus {
	if in == nil {
		return nil
	}
	out := new(LoadBalancerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ZoneRef) DeepCopyInto(out *ZoneRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ZoneRef.
func (in *ZoneRef) DeepCopy() *ZoneRef {
	if in == nil {
		return nil
	}
	out := new(ZoneRef)
	in.DeepCopyInto(out)
	return out
}
